In [1]:
# in a graph where vertices are indistinguishable from every other...
# is it merely a function of number of edges and verticies?

import numpy as np

In [2]:
# consider the bipartite graph K_{3,3}
# its 'markov matrix' <- made up term
# is as follows:
l3 = -1/3.0
k33 = np.array([
    [ 1,  0, l3, l3, l3],
    [ 0,  1, l3, l3, l3],
    [l3, l3,  1,  0,  0],
    [l3, l3,  0,  1,  0],
    [l3, l3,  0,  0,  1],
])
k33

array([[ 1.        ,  0.        , -0.33333333, -0.33333333, -0.33333333],
       [ 0.        ,  1.        , -0.33333333, -0.33333333, -0.33333333],
       [-0.33333333, -0.33333333,  1.        ,  0.        ,  0.        ],
       [-0.33333333, -0.33333333,  0.        ,  1.        ,  0.        ],
       [-0.33333333, -0.33333333,  0.        ,  0.        ,  1.        ]])

In [3]:
# consider the graph of a triangular prism
# its 'markov matrix' <- made up term
# is as follows:
tpg = np.array([
    [ 1, l3,  0, l3,  0],
    [l3,  1,  0,  0, l3],
    [ 0,  0,  1, l3, l3],
    [l3,  0, l3,  1, l3],
    [ 0, l3, l3, l3,  1],
])
print tpg

[[ 1.         -0.33333333  0.         -0.33333333  0.        ]
 [-0.33333333  1.          0.          0.         -0.33333333]
 [ 0.          0.          1.         -0.33333333 -0.33333333]
 [-0.33333333  0.         -0.33333333  1.         -0.33333333]
 [ 0.         -0.33333333 -0.33333333 -0.33333333  1.        ]]


In [5]:
# solve each, and compare average solution times.
costs = np.ones(5)
k33_moves = np.linalg.solve(k33, costs)
tpg_moves = np.linalg.solve(tpg, costs)
print k33_moves.sum() / 6.0
print tpg_moves.sum() / 6.0

4.5
4.7
